var express = require("express");
var router = express.Router();
const class_list = {
  categories: ["class", "brands", "location"],
  class: {
    Antiinfectives: [
      {
        id: 1,
        name: "Augmentin 625mg",
        generic_name: "Amoxicilin + Clavulanic Acid",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 2,
        name: "Ocefix 200mg",
        generic_name: "Cefixim",
        price: 30500,
        company: "meNorKnow",
        pack_size: 1000,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 3,
        name: "Axaxim 500mg",
        generic_name: "Cefuroxime",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 4,
        name: "Beecham 500mg",
        generic_name: "Amoxicillin 500mg",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 5,
        name: "Emgyl 200mg",
        generic_name: "Metrondazole",
        price: 53000,
        company: "Emzor",
        pack_size: 30,
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
        formulation: "Tablet",
      },
    ],
    AntiHypertensives: [
      {
        id: 6,
        name: "Norvasc 10mg",
        generic_name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 7,
        name: "Zenopril 10mg",
        generic_name: "Lisinopril",
        price: 30500,
        company: "kpako",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 8,
        name: "Amlodipine 10mg",
        generic_name: "Amlodipine",
        price: 34000,
        company: "Teva",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 9,
        name: "Nifecure",
        generic_name: "Nifedipine",
        price: 53000,
        strength: "30mg",
        company: "meNorKnw",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Antidiabetics: [
      {
        id: 10,
        name: "Glucophage",
        generic_name: "Metformin",
        price: 60000,
        company: "zanku",
        pack_size: 30,
        formulation: "Tablet",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 11,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 12,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 13,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    AntiHistamins: [
      {
        id: 14,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 15,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 16,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 17,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Antincancer: [
      {
        id: 18,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 19,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 20,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 21,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Vertigo: [
      {
        id: 22,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 23,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 24,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 25,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    "Alpha-Blockers": [
      {
        id: 26,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 27,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 28,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 29,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    AntiDepressants: [
      {
        id: 30,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 31,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 32,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 33,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Antispasmodic: [
      {
        id: 34,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 35,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 36,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 37,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Analgesics: [
      {
        id: 38,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 39,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 40,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 41,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
    Anathesia: [
      {
        id: 42,
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 43,
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 44,
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
      {
        id: 45,
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
        quantity: 0,
      },
    ],
  },
  brands: {
    Emzor: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    GSK: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    "M&B": [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Fidson: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Orange: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Pharmatex: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Pablo: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Lapaz: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Roche: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
  },
  location: {
    Lagos: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Onitcha: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Amoxicilin",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
    Kano: [
      {
        name: "Amlodipine",
        price: 60000,
        company: "Pfizer",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Diazepam",
        price: 30500,
        company: "koko",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Paracetamol",
        price: 34000,
        company: "M & B",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
      {
        name: "Becham Amoxil",
        price: 53000,
        company: "GSK",
        pack_size: 30,
        formulation: "Tablet",
        generic_name: "Amoxicillin",
        strength: "500mg",
        description:
          "one pill to prevent pregnancy and cure any std br the become serious",
        vendor: "name",
      },
    ],
  },
};
/* GET home page. */
router.get("/itemlist/:id", function (req, res, next) {
  const category = req.params.id;
  console.log(class_list.class[category]);
  res.send(
    JSON.stringify({
      category: class_list.class[category],
      categories: Object.keys(class_list.class),
    })
  );
});

module.exports = router;
